Revert "Add event limit and watermarks to HealthMonitor"
Revert submission 2364481

Reason for revert: Looks like this breaks the emulator build

See: 

17:13:40(12:19.43) bld | /buildbot/src/android/emu-master-dev/external/qemu/android/android-emugl/combined/impl/base/HealthMonitor.cpp:43:23: error: out-of-line definition of 'HealthMonitor<Clock>' does not match any declaration in 'HealthMonitor<Clock>'
17:13:40(12:19.90) bld | HealthMonitor<Clock>::HealthMonitor(MetricsLogger& metricsLogger, uint64_t heartbeatInterval)
17:13:40(12:19.10) bld | ^~~~~~~~~~~~~

Reverted changes: /q/submissionid:2364481

Change-Id: If5d53a1a8606121c9eb20b21986cee87b931c511